import { useState } from 'react'
import { navigate } from '../../utils/navigation'
import { Link } from '../../components/Link'
import { Logo } from '../../components/Logo'
import { Icon } from '../../components/Icon'
import { Button } from '../../components/Button'
function AuthLayout({ title, text, eyebrow, children }) { return <div className="auth-page"><header className="auth-topbar"><div className="auth-topbar-inner"><Logo/><div className="auth-top-actions"><Link to="/login">Log in</Link><Button to="/register" variant="nav" size="sm">Sign up</Button></div></div></header><main className="auth-main"><div className="auth-glow auth-glow-one"/><div className="auth-glow auth-glow-two"/><div className="auth-content"><div className="auth-box"><div className="auth-heading"><span className="auth-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{children}</div><div className="auth-proof"><div className="auth-avatars"><span>JN</span><span>KM</span><span>BE</span><b>+12k</b></div><p>Join 12,000+ candidates preparing for their dream roles.</p></div></div></main><footer className="auth-footer"><div><Logo/><p>© 2026 InterviewAI. Precision in preparation.</p></div><nav><a href="/#features">Features</a><a href="/#how">How it works</a><a href="#">Privacy</a><a href="#">Terms</a><a href="mailto:hello@interviewai.cm">Contact</a></nav></footer></div> }
function Field({ label, type='text', placeholder, icon, hint }) { const [show,setShow] = useState(false); return <label className="field"><span>{label}</span><div><Icon name={icon} size={18}/><input type={show ? 'text' : type} placeholder={placeholder}/>{type==='password'&&<button type="button" aria-label={show ? 'Hide password' : 'Show password'} onClick={()=>setShow(!show)}><Icon name={show ? 'eyeOff' : 'eye'} size={17}/></button>}</div>{hint && <small className="field-note">{hint}</small>}</label> }
export function Login() { return <AuthLayout eyebrow="Welcome back" title="Sign in to InterviewAI" text="Continue building the confidence for your next opportunity."><form onSubmit={e=>{e.preventDefault();navigate('/home')}}><Field label="Email address" type="email" placeholder="you@example.com" icon="mail"/><Field label="Password" type="password" placeholder="Enter your password" icon="lock"/><div className="form-row"><label><input type="checkbox"/> Remember me</label><Link to="/forgot-password">Forgot password?</Link></div><Button type="submit" full endIcon="arrow">Sign in</Button></form><p className="auth-switch">New to InterviewAI? <Link to="/register">Create an account</Link></p></AuthLayout> }
export function Register() { return <AuthLayout eyebrow="Start for free" title="Create your account" text="Start your journey to interview mastery."><form onSubmit={e=>{e.preventDefault();navigate('/home')}}><Field label="Email address" type="email" placeholder="name@company.com" icon="mail"/><Field label="Password" type="password" placeholder="••••••••" icon="lock" hint="Must be at least 8 characters with a mix of letters and numbers."/><Field label="Confirm password" type="password" placeholder="••••••••" icon="lock"/><label className="terms"><input type="checkbox"/> <span>I agree to the <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a>.</span></label><Button type="submit" full endIcon="arrow">Register</Button></form><p className="auth-switch">Already have an account? <Link to="/login">Login</Link></p></AuthLayout> }
export function ForgotPassword() { const [sent,setSent] = useState(false); return <AuthLayout eyebrow="Account recovery" title={sent?'Check your email':'Reset your password'} text={sent?'We sent a reset link to your inbox.':"Enter your email and we'll send you a secure reset link."}>{sent?<div className="success-message"><span><Icon name="check"/></span><p>The link expires in 30 minutes.</p><Button to="/login" full>Back to sign in</Button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><Field label="Email address" type="email" placeholder="you@example.com" icon="mail"/><Button type="submit" full>Send reset link</Button><p className="auth-switch"><Link to="/login">← Back to sign in</Link></p></form>}</AuthLayout> }
