import { Router } from 'express'
import { z } from 'zod'
import { db } from '../../config/database.js'
import { AppError, asyncHandler, sendData } from '../../utils/http.js'
import { validate } from '../../utils/validation.js'
const jobSchema=z.object({jobTitle:z.string().trim().min(2).max(180),companyName:z.string().trim().max(180).nullable().optional(),description:z.string().trim().min(50).max(100000),experienceLevel:z.string().max(80).nullable().optional(),location:z.string().max(160).nullable().optional()})
const matchSchema=z.object({resumeId:z.coerce.number().int().positive(),jobDescriptionId:z.coerce.number().int().positive()})
export const jobRouter=Router()
jobRouter.get('/',asyncHandler(async(req,res)=>{const [rows]=await db.execute('SELECT id,job_title,company_name,experience_level,location,status,created_at FROM job_descriptions WHERE user_id=? ORDER BY created_at DESC',[req.session.userId]);sendData(res,rows)}))
jobRouter.post('/',validate(jobSchema),asyncHandler(async(req,res)=>{const j=req.body;const [result]=await db.execute('INSERT INTO job_descriptions (user_id,job_title,company_name,original_text,experience_level,location,status) VALUES (?,?,?,?,?,?,?)',[req.session.userId,j.jobTitle,j.companyName||null,j.description,j.experienceLevel||null,j.location||null,'analysed']);sendData(res,{id:result.insertId,...j},201)}))
jobRouter.get('/:id',asyncHandler(async(req,res)=>{const [rows]=await db.execute('SELECT * FROM job_descriptions WHERE id=? AND user_id=?',[req.params.id,req.session.userId]);if(!rows[0])throw new AppError(404,'Job description not found.');const [requirements]=await db.execute('SELECT id,category,value,required FROM job_requirements WHERE job_description_id=?',[req.params.id]);sendData(res,{...rows[0],requirements})}))
jobRouter.delete('/:id',asyncHandler(async(req,res)=>{const [result]=await db.execute('DELETE FROM job_descriptions WHERE id=? AND user_id=?',[req.params.id,req.session.userId]);if(!result.affectedRows)throw new AppError(404,'Job description not found.');res.status(204).end()}))
jobRouter.post('/match/calculate',validate(matchSchema),asyncHandler(async(req,res)=>{const {resumeId,jobDescriptionId}=req.body;const [resumes]=await db.execute('SELECT extracted_text FROM resumes WHERE id=? AND user_id=?',[resumeId,req.session.userId]);const [jobs]=await db.execute('SELECT original_text FROM job_descriptions WHERE id=? AND user_id=?',[jobDescriptionId,req.session.userId]);if(!resumes[0]||!jobs[0])throw new AppError(404,'Resume or job description not found.');const tokens=(s)=>new Set((s||'').toLowerCase().match(/[a-z][a-z+#.]{2,}/g)||[]);const cv=tokens(resumes[0].extracted_text),job=tokens(jobs[0].original_text);const overlap=[...job].filter(x=>cv.has(x));const missing=[...job].filter(x=>!cv.has(x)).slice(0,15);const score=Math.max(10,Math.min(100,Math.round((overlap.length/Math.max(job.size,1))*140)));const [result]=await db.execute('INSERT INTO resume_job_matches (user_id,resume_id,job_description_id,overall_score,skills_score,strong_skills,missing_skills,recommendations) VALUES (?,?,?,?,?,?,?,?)',[req.session.userId,resumeId,jobDescriptionId,score,score,JSON.stringify(overlap.slice(0,15)),JSON.stringify(missing),JSON.stringify(['Add measurable results','Reflect important role keywords naturally'])]);sendData(res,{id:result.insertId,overallScore:score,strongSkills:overlap.slice(0,15),missingSkills:missing},201)}))
