import { Router } from 'express'
import { z } from 'zod'
import { db } from '../../config/database.js'
import { AppError, asyncHandler, sendData } from '../../utils/http.js'
import { validate } from '../../utils/validation.js'
import { buildQuestionSet } from '../../services/question-bank.service.js'
const createSchema=z.object({targetRole:z.string().trim().min(2).max(180),type:z.enum(['hr','behavioral','technical','situational','problem_solving','mixed']).default('mixed'),resumeId:z.number().int().positive().nullable().optional(),jobDescriptionId:z.number().int().positive().nullable().optional(),questionCount:z.number().int().min(3).max(20).default(8)})
const answerSchema=z.object({answerText:z.string().trim().min(1).max(20000),durationSeconds:z.number().int().min(0).max(7200).optional()})
export const interviewRouter=Router()
interviewRouter.get('/',asyncHandler(async(req,res)=>{const [rows]=await db.execute('SELECT id,target_role,interview_type,status,overall_score,started_at,completed_at,created_at FROM interview_sessions WHERE user_id=? ORDER BY created_at DESC',[req.session.userId]);sendData(res,rows)}))
interviewRouter.post('/',validate(createSchema),asyncHandler(async(req,res)=>{const d=req.body,questions=buildQuestionSet(d.type,d.questionCount),c=await db.getConnection();try{await c.beginTransaction();const [result]=await c.execute('INSERT INTO interview_sessions (user_id,resume_id,job_description_id,target_role,interview_type,status,started_at) VALUES (?,?,?,?,?,?,NOW())',[req.session.userId,d.resumeId||null,d.jobDescriptionId||null,d.targetRole,d.type,'in_progress']);for(const [i,q] of questions.entries())await c.execute('INSERT INTO interview_questions (interview_session_id,question_type,question_text,sort_order) VALUES (?,?,?,?)',[result.insertId,q.questionType,q.questionText,i+1]);await c.commit();sendData(res,{id:result.insertId,status:'in_progress',questions},201)}catch(e){await c.rollback();throw e}finally{c.release()}}))
interviewRouter.get('/:id',asyncHandler(async(req,res)=>{const [sessions]=await db.execute('SELECT * FROM interview_sessions WHERE id=? AND user_id=?',[req.params.id,req.session.userId]);if(!sessions[0])throw new AppError(404,'Interview not found.');const [questions]=await db.execute('SELECT q.id,q.question_type,q.question_text,q.sort_order,a.answer_text,a.overall_score,a.feedback FROM interview_questions q LEFT JOIN interview_answers a ON a.question_id=q.id WHERE q.interview_session_id=? ORDER BY q.sort_order',[req.params.id]);sendData(res,{...sessions[0],questions})}))
interviewRouter.post('/:id/questions/:questionId/answer',validate(answerSchema),asyncHandler(async(req,res)=>{const [owned]=await db.execute('SELECT q.id FROM interview_questions q JOIN interview_sessions s ON s.id=q.interview_session_id WHERE q.id=? AND s.id=? AND s.user_id=?',[req.params.questionId,req.params.id,req.session.userId]);if(!owned[0])throw new AppError(404,'Interview question not found.');await db.execute('INSERT INTO interview_answers (question_id,answer_text,duration_seconds) VALUES (?,?,?) ON DUPLICATE KEY UPDATE answer_text=VALUES(answer_text),duration_seconds=VALUES(duration_seconds),submitted_at=NOW()',[req.params.questionId,req.body.answerText,req.body.durationSeconds||null]);await db.execute('UPDATE interview_sessions SET current_question=current_question+1 WHERE id=?',[req.params.id]);sendData(res,{message:'Answer saved. Evaluation will be available when an AI provider is connected.'},201)}))
interviewRouter.post('/:id/complete',asyncHandler(async(req,res)=>{const [result]=await db.execute("UPDATE interview_sessions SET status='completed',completed_at=NOW(),overall_score=(SELECT ROUND(AVG(a.overall_score)) FROM interview_questions q JOIN interview_answers a ON a.question_id=q.id WHERE q.interview_session_id=?) WHERE id=? AND user_id=?",[req.params.id,req.params.id,req.session.userId]);if(!result.affectedRows)throw new AppError(404,'Interview not found.');sendData(res,{message:'Interview completed.'})}))
